<a href="https://colab.research.google.com/github/faisu6339-glitch/Data-Analytic/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[2,54,5,5,6],[5,8,7,9,7]])
print(arr)
arr.shape

[[ 2 54  5  5  6]
 [ 5  8  7  9  7]]


(2, 5)

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.zeros([4,3],
         dtype=np.int32,
         order='f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
np.empty([4,3])

array([[5.39098329e-315, 0.00000000e+000, 2.10077583e-312],
       [6.79038654e-313, 2.22809558e-312, 2.14321575e-312],
       [2.35541533e-312, 6.79038654e-313, 2.22809558e-312],
       [2.14321575e-312, 2.46151512e-312, 2.41907520e-312]])

In [ ]:
np.random()

TypeError: 'module' object is not callable

In [ ]:
np.ones([4,3])

Arithmetic Operation

In [ ]:
a=np.array([1,2,3,1,6,6])
b=np.array([10,28,35,15,26,56])
print("Addition of a+b=",a+b)
print(a-b)
print(a*b)
print(a/b)

Aggregation Function

In [ ]:
arr=np.array([[1,2,3,4],[8,9,7,5]])
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("Products of all element:",np.prod(arr))
print("Standard Deviation:",np.std(arr))

In [ ]:
import numpy as np

a = np.random.rand(5)
print(a)

In [ ]:
b = np.random.rand(2, 3)
print(b)

In [ ]:
#np.random.randn()

In [ ]:
z = np.random.randint(1, 10, size=5)
print(z)


In [ ]:
#➡️ 2D matrix example:

In [ ]:
m = np.random.randint(0, 100, (3, 4))
print(m)


In [ ]:
arr1=np.array([[4,5,7,8,5],[12,45,69,78,50]])
print("Array\n",arr1)
print("Shape\n:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Size:", arr1.size)

In [ ]:
import numpy as np

arr = np.arange(6)
new_arr = arr.reshape(2, 3)

print("Original:", arr)
print("Reshaped:\n", new_arr)


In [ ]:
arr = np.arange(12)
new_arr = arr.reshape(3, -1)

print(new_arr)


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

flat=arr.flatten()
print(flat)

arr2=arr.reshape(2,4)
print(arr2)

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

rv = arr.ravel()

print("Ravel:", rv)

rv[1] = 20
print("Modified ravel:", rv)
print("Original arr:\n", arr)


Indexing


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # first element
print(arr[2])   # third element
print(arr[-1])  # last element (negative index)


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[0,0])  # first row, first column
print(arr[1,2])  # second row, third column
print(arr[-1,-1])# last row, last column


1
6
9


Slicing

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80])
print(arr[1:4])    # from index 1 to 3
print(arr[:3])     # start → index 0
print(arr[3:])     # index 3 to end
print(arr[::2])    # every 2nd element


[20 30 40]
[10 20 30]
[40 50 60 70 80]
[10 30 50 70]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[0:2, 1:3])


[[2 3]
 [5 6]]


In [ ]:
print(arr[:,1])   # all rows, 2nd column
print(arr[1,:])   # 2nd row, all columns


[2 5 8]
[4 5 6]


In [ ]:
print(arr[::2, ::2])


[[1 3]
 [7 9]]


Filter

In [ ]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr > 15])


[20 25]


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

mask = arr % 2 == 0   # even numbers
print(arr[mask])


[2 4 6 8]


In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[[0,3,4]])


[10 40 50]


In [ ]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr[[0,2], [1,2]])


[20 90]


📌 1. Creating Matrices

In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8,9],
              [10,11,12]])

print(A)
print(B)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
C = A + B
print("Addition:\n", C)
D = A - B
print("Subtraction:\n", D)
print("Multiply by 2:\n", A * 2)
print("Add 10:\n", A + 10)
E = A * B
print("Element-wise Multiply:\n", E)



Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiply by 2:
 [[ 2  4  6]
 [ 8 10 12]]
Add 10:
 [[11 12 13]
 [14 15 16]]
Element-wise Multiply:
 [[ 7 16 27]
 [40 55 72]]


In [ ]:
X = np.array([[1,2],
              [3,4],
              [5,6]])

Y = np.array([[1,2,3],
              [4,5,6]])

print("Matrix Multiply:\n", X.dot(Y))


Matrix Multiply:
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [ ]:
print("Transpose:\n", A.T)


Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
print("Transpose:\n", B.T)


Transpose:
 [[ 7 10]
 [ 8 11]
 [ 9 12]]


In [ ]:
M = np.array([[2,3],
              [4,1]])

det = np.linalg.det(M)
print(det)


-10.000000000000002


In [ ]:
I = np.eye(4)
print(I)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.zeros((3,3)))
print(np.ones((2,4)))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
d = np.diag([2,3,4,5])
print(d)


[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [ ]:
M = np.array([[1,2,3],
              [4,5,6]])

v = np.array([10,20,30])

print(M + v)


[[11 22 33]
 [14 25 36]]


In [ ]:
data = np.array([[1,2,3],
                 [4,5,6]])

mean = data.mean(axis=0)
std = data.std(axis=0)

normalized = (data - mean) / std
print(normalized)


[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [ ]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

cov = np.cov(X.T)
print(cov)


[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


📌 4. prod(), cumulative sum, cumulative product

In [ ]:
arr = np.array([1,2,3,4])

print("Product:", arr.prod())
print("Cumulative Sum:", arr.cumsum())
print("Cumulative Product:", arr.cumprod())


Product: 24
Cumulative Sum: [ 1  3  6 10]
Cumulative Product: [ 1  2  6 24]


📌 5. min / max with index → argmin(), argmax()

In [ ]:
arr = np.array([10, 3, 25, 7, 9])
print("Minimum index:", np.argmin(arr))
print("Maximum index:", np.argmax(arr))


Minimum index: 1
Maximum index: 2


📌 6. Percentile / Median

In [ ]:
arr = np.array([1,3,5,7,9])

print("Median:", np.median(arr))
print("25th percentile:", np.percentile(arr, 25))
print("75th percentile:", np.percentile(arr, 75))


Median: 5.0
25th percentile: 3.0
75th percentile: 7.0


📌 7. Standard Deviation & Variance

In [ ]:
arr = np.array([1,2,3,4,5])

print("Mean:", arr.mean())
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))


Mean: 3.0
Variance: 2.0
Standard Deviation: 1.4142135623730951


📌 9. Boolean Aggregations

In [ ]:
arr = np.array([2,4,6,8])

print(arr > 5)
print("Any >5?:", np.any(arr > 5))
print("All even?:", np.all(arr % 2 == 0))


[False False  True  True]
Any >5?: True
All even?: True


In [ ]:
arr = np.array([10,21,32,41,50])

even_numbers = arr[arr % 2 == 0]
print("Even numbers:", even_numbers)
print("Sum of evens:", even_numbers.sum())


Even numbers: [10 32 50]
Sum of evens: 92


🔥 1. Stacking Arrays

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
print(c)


[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack((a, b))
print(c)


[1 2 3 4 5 6]


🔥 2. np.concatenate()

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b), axis=0)
print(c)


[1 2 3 4 5 6]


In [ ]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6]])

C = np.concatenate((A, B), axis=0)
print(C)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

C = np.concatenate((A, B), axis=1)
print(C)


[[1 2 5 6]
 [3 4 7 8]]


🔥 3. Splitting Arrays

In [ ]:
a = np.array([1,2,3,4,5,6])
x = np.split(a, 3)
print(x)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
A = np.array([[1,2],
              [3,4],
              [5,6]])

result = np.split(A, 3, axis=0)
print(result)


[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


➤ Split columns — axis=1

In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])

result = np.split(A, 3, axis=1)
print(result)


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


Filtering & Masking

Data cleaning

Boolean masks + conditions chaining

In [ ]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30])
mask = arr > 20
print(mask)


[False False False  True  True]


In [ ]:
filtered = arr[mask]
print(filtered)


[25 30]


AND condition

Keep numbers between 10 and 25

In [ ]:
arr[(arr >= 10) & (arr <= 25)]


array([10, 15, 20, 25])

Broadcasting

In [ ]:
import numpy as np
a=np.array([1,4,5,6,4,5])
b=10
c=5
print(a+b)
print(a*c)

[11 14 15 16 14 15]
[ 5 20 25 30 20 25]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)


[11 22 33]


4️⃣ 2D + 1D Broadcasting

In [ ]:
a = np.array([1, 2, 3,5])
bias=np.array([[1,2,3,4],[4,8,9,7]])
z=a+bias
print(z)


[[ 2  4  6  9]
 [ 5 10 12 12]]


Example 2: Add a column vector to each row (need reshape)

In [ ]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])      # shape (3, 3)

row_bias = np.array([10, 100, 1000])   # shape (3,)

# Make it a column vector: shape (3, 1)
row_bias_col = row_bias.reshape(-1, 1)

Y = X + row_bias_col
print(Y)


[[  11   12   13]
 [ 104  105  106]
 [1007 1008 1009]]


Example 1: Feature Scaling (Normalization per column)

In [ ]:
X = np.array([[1.,  2.,  3.],
              [4.,  5.,  6.],
              [7.,  8.,  9.]])

# Column-wise mean and std → shape (3,)
mean = X.mean(axis=0)
std = X.std(axis=0)

print("mean:", mean)
print("std:", std)

X_norm = (X - mean) / std
print("Normalized X:\n", X_norm)


mean: [4. 5. 6.]
std: [2.44948974 2.44948974 2.44948974]
Normalized X:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [ ]:
scores = np.array([[1.2, 0.5, 2.1],
                   [0.3, 1.8, 2.5],
                   [2.0, 0.1, 1.0]])   # shape (3, 3)

bias = np.array([0.1, -0.2, 0.05])    # shape (3,)

adjusted_scores = scores + bias
print(adjusted_scores)


[[ 1.3   0.3   2.15]
 [ 0.4   1.6   2.55]
 [ 2.1  -0.1   1.05]]


In [ ]:
images = np.ones((2, 3, 3))   # 2 images, 3x3 each
scale = np.array([1, 2, 3])   # shape (3,)

# We want to scale each column differently → make it (1,1,3)
scale_reshaped = scale.reshape(1, 1, 3)

result = images * scale_reshaped
print("result shape:", result.shape)
print(result[0])


result shape: (2, 3, 3)
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
a = np.ones((3, 3))
b = np.array([1, 2,3])
a + b


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

Python Loops vs NumPy Vectorization

In [ ]:
data = [1, 2, 3, 4, 5]
result = []
for x in data:
    result.append(x * 2)
print(result)


[2, 4, 6, 8, 10]


In [ ]:
import numpy as np
data = np.array([1,2,3,4,5])
print(data * 2)


[ 2  4  6  8 10]


In [ ]:
arr = np.arange(1000000)
res = arr * 2
print(res)

[      0       2       4 ... 1999994 1999996 1999998]


In [ ]:
a = np.array([1,2,3])
print(a + 5)
print(a * 10)


[6 7 8]
[10 20 30]


In [ ]:
x = np.array([1,2,3])
y = np.array([10,20,30])
print(x + y)


[11 22 33]


4️⃣ Vectorized Mathematical Functions

In [ ]:
arr = np.array([1,2,3,4])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))


[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

bias = np.array([10,20,30])
print(X + bias)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


Normalize Dataset (Mean & Std per Feature)

In [ ]:
import numpy as np

# Dataset: rows = samples, columns = features
X = np.array([
    [1., 10., 100.],
    [2., 20., 200.],
    [3., 30., 300.]
])

# mean/std computed for each feature (shape: (3,))
mean = X.mean(axis=0)
std  = X.std(axis=0)

# Vectorized + Broadcasting
X_norm = (X - mean) / std

print("Mean:", mean)
print("Std:", std)
print("Normalized X:\n", X_norm)



Mean: [  2.  20. 200.]
Std: [ 0.81649658  8.16496581 81.64965809]
Normalized X:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [ ]:
import numpy as np

X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

weights = np.array([0.1, 0.2, 0.3])

result = X * weights
print(result)


[[0.1 0.4 0.9]
 [0.4 1.  1.8]
 [0.7 1.6 2.7]]


In [ ]:
import numpy as np

x = np.array([
    [1, -1, 2],
    [3, 0, -4]
])

sigmoid = 1 / (1 + np.exp(-x))
print(sigmoid)


[[0.73105858 0.26894142 0.88079708]
 [0.95257413 0.5        0.01798621]]
