In [ ]:
#Insert

In [1]:
import numpy as np

In [ ]:
#1d-Array

In [4]:
var=np.array([1,2,3,4,5,])
print(var)

np.insert(var,0,9)

[1 2 3 4 5]


array([9, 1, 2, 3, 4, 5])

In [6]:
var1=np.array([1,2,3,4,5,6])
print(var1)

np.insert(var,(0,1),55)

[1 2 3 4 5 6]


array([55,  1, 55,  2,  3,  4,  5])

In [ ]:
#2d-Array

In [12]:
var2=np.array([[1,2,3],[4,5,6]])
v2=np.insert(var2,0,55,axis=1)
print(v2)

[[55  1  2  3]
 [55  4  5  6]]


In [ ]:
#Multiple Data Passing

In [13]:
var3=np.array([[1,2,3],[4,5,6]])
v3=np.insert(var3,2,[22,33],axis=1)
print(v3)

[[ 1  2 22  3]
 [ 4  5 33  6]]


In [ ]:
#Insert data using append function

In [14]:
var4=np.array([1,2,3,4,5,])
print(var4)
x=np.append(var4,6.5)
print(x)

[1 2 3 4 5]
[1.  2.  3.  4.  5.  6.5]


In [ ]:
#Delete

In [15]:
var5=np.array([1,2,3,4,5,])
print(var5)
d=np.delete(var5,1)
print(d)

[1 2 3 4 5]
[1 3 4 5]
