In [ ]:
#Join Array


In [1]:
import numpy as np

In [ ]:
#1D- ARRAY

In [2]:
var=np.array([1,2,3,4,])
var1=np.array([5,6,7,8,9])
arr=np.concatenate((var,var1))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#2D- ARRAY

In [5]:
var2=np.array([[1,2],[3,4,]])
var3=np.array([[5,6,],[8,9]])
arr1=np.concatenate((var2,var3),axis=1)
print(var2)
print()
print(var3)
print()
print(arr1)

[[1 2]
 [3 4]]

[[5 6]
 [8 9]]

[[1 2 5 6]
 [3 4 8 9]]


In [ ]:
#Using stack function

In [7]:
var4=np.array([1,2,3,4,])
var5=np.array([5,6,8,9])
arr2=np.stack((var4,var5),axis=1)
print(var4)
print()
print(var5)
print()
print(arr2)

[1 2 3 4]

[5 6 8 9]

[[1 5]
 [2 6]
 [3 8]
 [4 9]]
