#Zeros

In [1]:
import numpy as np


In [9]:
arr_zero=np.zeros(4)
arr_zero1=np.zeros((3,4))

print(arr_zero)
print()
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
arr_one=np.ones(5)
arr_one1=np.ones((6,4))
print(arr_one)
print(arr_one1)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Creating an empty array

In [11]:
arr_em=np.empty(4)
print(arr_em)

[0. 0. 0. 0.]


In [ ]:
#Creating a range of an array

In [12]:
arr_rn=np.arange(4)
print(arr_rn)

[0 1 2 3]


In [ ]:
#Diagonal filled with one 1

In [13]:
arr_dia=np.eye(5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
arr_dia1=np.eye(3,5)
print(arr_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
#Line space function

In [18]:
arr_line=np.linspace(0,20,num=5)
print(arr_line)

[ 0.  5. 10. 15. 20.]
