In [4]:
import numpy as np

In [ ]:
#shuffle

In [6]:
var =np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[2 4 1 3 5]


In [ ]:
#unique

In [15]:
var1 =np.array([1,2,3,4,5,6,1,1,2,1,2,3,3,4,5])
x=np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64), array([4, 3, 3, 2, 2, 1], dtype=int64))


In [ ]:
#resize

In [17]:
var2 =np.array([1,2,3,4,5,6,])
y=np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
#flatten

In [23]:
var3 =np.array([11,22,33,44,55,66,])
z=np.resize(var3,(2,3))
print(z)
print()
print(z.flatten())

[[11 22 33]
 [44 55 66]]

[11 22 33 44 55 66]
