In [ ]:
#Random

In [ ]:
#1.rand() function

In [1]:
import numpy as np

In [2]:
var=np.random.rand(9)
print(var)

[0.59929156 0.08323618 0.35011582 0.09351529 0.29422591 0.16559213
 0.21828082 0.30863896 0.07679343]


In [4]:
var1=np.random.rand(2,5)
print(var1)

[[0.61604735 0.22311928 0.75012361 0.99087861 0.85591133]
 [0.34042867 0.01489437 0.40327391 0.66018981 0.09384226]]


In [ ]:
#2.randn() function

In [6]:
var2=np.random.randn(9)
print(var2)

[ 1.06939518 -0.15454971 -0.25624046 -0.88766505 -0.47422829  0.42535596
  0.83834821  0.37134332 -1.83663023]


In [ ]:
#3.randf() function

In [7]:
var3=np.random.ranf(8)
print(var3)

[0.1133972  0.94319832 0.40897775 0.07661703 0.67724452 0.42186847
 0.27021288 0.05075167]


In [ ]:
#4.randint() function

In [9]:
var4=np.random.randint(6,24,7)
print(var4)

[10  7 23 23  9 22  8]
