In [ ]:
#shapes and Reshaping in arrays

In [ ]:
#Shapes

In [4]:
import numpy as np
var=np.array([[1,2],[1,2]])
print(var)

print(var.shape)

[[1 2]
 [1 2]]
(2, 2)


In [6]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
print(var1)

print(var1.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


In [9]:
var2=np.array([1,2,3,4,5,6,],ndmin=4)
print(var2)
print(var2.ndim)
print(var2.shape)

[[[[1 2 3 4 5 6]]]]
4
(1, 1, 1, 6)


In [ ]:
#Conversion of array shape in different forms

In [ ]:
#Reshape

In [14]:
var3=np.array([1,2,3,4,5,6])
print(var3)
print(var3.ndim)
print()

x=var3.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [15]:
var4=np.array([1,2,3,4,5,6,1,2,3])
print(var4)
print(var4.ndim)
print()

x=var4.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6 1 2 3]
1

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2


In [ ]:
#Creating three dimensional array

In [17]:
var5=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var5)
print(var5.ndim)
print()

x1=var5.reshape(2,3,2)
print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
#Conversion of thre dimensional array to one dimensional array

In [18]:
var5=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var5)
print(var5.ndim)
print()

x1=var5.reshape(2,3,2)
print(x1)
print(x1.ndim)
print()

one=x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
